Maze #1
EEEEE

Maze #2
Impossible.

Maze #3
eennwwWWWWeeeeeesswwwwwwwnNN

Maze #4
swwwnnnnnneeesssSSS

Maze #5
eennwwWWWWeeeeeesswwwwwwwnNN

Maze #6
wsseenN

Maze #7
WWWswNNseeeeeennnnwwwwwwwssEEEE

Maze #8
EwnnnnnnneessssssSS

Maze #9
Impossible.

Maze #10
E

Maze #11
W

Maze #12
N

Maze #13
eesWnwS

Maze #14
eSwsEneSwsEneSwsEneSwsEneSwsEneSwsEneSwsEneSwsEneSwsEneSwsEE

Maze #15
nwwwnnnwwnneSwwsssseeennnWWnwSSSnnwwssseEEEEEEEEEEseNenW

Maze #16
sseesssssssssssssseennnnnnneeeeEEwwwwwwsseeeeeeenennwSSesWWWWWWWeeeeeennwwwwwwwsSSSSSneeeeeeeeenennnnnnnnnnwwwwwwwwwwnwwsssssssssssssseEEEEEEEEEEEEEseNNNNNNNwnEEwnnnnnnwwwwwwwwwwwwwnwwwwnneeeeeeeeeeeeeeeeeeessssssssSSSSSSSSSS

Maze #17
wwssseeeeeeennnnnnnwwwwwwwwwwwssssssssssseeeeeeeeeeeeeeennnnnnnnnnnnnnnwwwwwwwwwwwwwwwwwnneeeeeeeeeeeeeeeeeeessssssssssssssssssswwwwwwwwwwwwwwwwwwwnnnnnnnnnnnnnnneeeeeeeeeeeeeeessssssssssswwwwwwwwwwwnnnnnnneeeeesS

Maze #18
EwsseeeseeennnnnnnwwwwwwwwwwwssssssssssseeeeeeeeeeeeeeennnnnnnnnnnnnnnwwwwwwwwwwwwwwwwwnneeeeeeeeeeeeeeeeeeessssssssssssssssssswwwwwwwwwwwwwwwwwwwnnnnnnnnnnnnnnneeeeeeeeeeeeeeessssssssssswwwwwwwwwwwnnnnnnneeeeesSSnnnwwwwwssssssseeeeeeeeeeennnnnnnnnnnwwwwwwwwwwwwwwwssssssssssssssseeeeeeeeeeeeeeeeeeennnnnnnnnnnnnnnnnnnwwwwwwwwwwwwwwwwwwwsseeeeeeeeeeeeeeeeessssssssssssssswwwwwwwwwwwwwwwnnnnnnnnnnneeeeeeeeeeessssssswwwnWWennwwsS

Maze #19
EEEEEEEEEEEEEEEEEneSSSSSSSSSSSSSSSSSesWWWWWWWWWWWWWWWWWswNNNNNNNNNNNNNNNwnEEEEEEEEEEEEEEEwssssssssssseesseennnnnnnnnnnnnnnwwsSSSSSSSSSSSSSnnnnnnnnnnnnnneessssssssssssssswWWWWWWWWWWWWWennnnnnnnnwwnnwwssssssssssssseenNNNNNNNNNNNsssssssssssswwnnnnnnnnnnnnneEEEEEEEEEEEwwwwwwwwwwwwnneeeeeeeeeeeeesSSSSSSSSSnnnnnnnnnneessssssssssswWWWWWWWWWeeeeeeeeeesswwwwwwwwwwwnNNNNNNNsssssssswwnnnnnnnnneEEEEEEEwwwwwwwwnneeeeeeeeesSSSSSnnnnnneessssssswWWWWWeeeeeesswwwwwwwnNNNsssswwnnnnneEEEwwwwnneeeeesSS

Maze #20
EneSSnneessswWWennwwsSSSesesswwsssswwnnnnnneEEneSSSnnnwwnneeeenneesseessswwwwssswWWnwSSSnnenennwwwwsssssseEEneSSSwwssseeseeeeeennwwnnnnwwssswWWnwSSSnnenennwwwwsssssseEEEEEEEEwwwwwnwwnneeeennneessseeeeseeeesswwwwswwNNNssseeneeeennwwwwnwWWswNNNssseesswwwwwwwnwnneeeennneEEseNNNsswwssseeeeseennneennnwwwwnwWWswNNNsseessswwwwssswwnnnnwwnneeeennneEEseNNNwwnnneeeeeessswwnwWWswNNseeeeseennnwwwwnwwwsEEEEEEneSSSnnwwwwwwsseeeeseEEneSSSnnwwnnneeneeesswsssesswwWWnwSSSnneennnwwwwnwwssswwssseeeeseEEneSSSwwssseessseenennwnnwWWnwSSSesesswwwwswwnnnneeseEEneSSnwwwwnwwsssseeneeeEEwnnwwnnneeeessesswSwsE

Maze #21
essesesseeseseseeeesseeessssessessseeNNNNNNNNNNNNNNNNNenWWWWWWWWWWWWWWWWW

Maze #22
Impossible.

Maze #23
Impossible.

Maze #24
sSSSSSSSSSSSSSSSSS

Maze #25
eesswwsseesswwsseesswwsseesswwsseesswwsE

Maze #26
wwwwwwwwwwwwwwwwwW

